const LINES = [
  'cadre - the model-agnostic harness (experiment; wraps ax + any provider)',
  '',
  '  cadre go "<outcome>"     the one command - scan the room, form the crew, run',
  '                           plan/build/critique/verify, gate on evidence',
  '    --dry                    routing + pipeline only, spends nothing',
  '    --impl <ax-lane>         pin the builder lane',
  '    --budget <tokens>        cap metered spend for this run',
  '    --scope <glob>           scope lock: diff outside it = run rejected',
  '    --done <statement>       extra done-condition: a command, or keywords the diff must carry',
  '    --context <file>         attach a file as context for ax build',
  '    --override               explicit: keep a degrading preference, skip quiet hours',
  '    --role <role>=<lane>     explicit one-run override of who does the role',
  '    --resume <run-id>        continue a checkpointed run',
  '  cadre init               scaffold $CADRE_HOME with an example lane (idempotent)',
  '  cadre doctor             cold-machine preflight: one fix line per problem',
  '  cadre --version          print cadre <semver>',
  '  cadre lanes [--json]     live roster: ax registry + env-keyed APIs + yours',
  '  cadre parity "<outcome>" --ref <path|id>',
  '                           one ax build against a reference (does not close each behavior)',
  '  cadre parity --until-proven --ref <file>',
  '                           loop until each named check passes; "beyond parity" builds stretch after',
  '  cadre plan "<task>"      routing + spend estimate + bench ranking from history',
  '  cadre meter [--set ...]  entitlement ledger: quotas, resets, pacing, real burn',
  '                           --set lane=L --quota N --reset ISO [--rail official]',
  '  cadre sweep [--all]      triage leftovers: evidence snapshot, retire or resume',
  "                           --forget <run-id> retract that run's memory claims",
  '                                           (hand ledger + preference events)',
  '  cadre map [--why <sym>]  index this repo (symbols, imports, hot zones)',
  '  cadre proof <run-id>     evidence bundle; --verify re-runs commands vs reality',
  '  cadre watch <run-id>     tail a run log live; --replay prints the settled log',
  '  cadre debate "<q>"       two ax lanes argue; transcripts cited',
  '  cadre pin [...]          --role <r>=<l> · --budget <tok> · --quiet HH:MM-HH:MM',
  '  cadre mcp                MCP server on stdio (12 tools: lanes, plan, map, proof, meter,',
  '                           go [dry default; live returns run id], status [read-only], sweep,',
  '                           watch, parity, debate, doctor; pin stays terminal-only)',
  '  cadre retract <id> --why "<reason>"',
  '                           pull a run\'s claims: stains runs that folded its evidence,',
  '                           rebuilds the recall index; retracted/stale never count as history',
  '  cadre recall [text] [--file f] [--lane l] [--status s] [--limit n] [--rebuild]',
  '                           ask the ledger: runs by brief text, file, lane, or status',
  '',
  'state: $CADRE_HOME (default ~/.cadre) · runs (with locks), pins, meters, maps, audit.log',
  'chat lanes: any OpenAI-compatible env-keyed provider (see scan) enables drafting',
];

export function cmdHelp() {
  console.log(LINES.join('\n'));
}
